### PR TITLE
Implement seed config

### PR DESCRIPTION
**Pull request by maennchen**
Implementation of #8

@strzibny I'd like your feedback on this PR.

### CODE REVIEW

**Comment by strzibny** [comment]
Not sure if I understood it right, but now the `refresh` also uses the `seed` function? This is what I wouldn't want. I need initial seed, but use the library to download fresh rates. Maybe that's why I did not use the `case` statement in your original form since it always called to `refresh` first even on `:manual`. But maybe I am missing something.

**Comment by maennchen** [comment]
The `seed` function is only used in the `init` function: https://github.com/jshmrtn/currency-conversion/pull/20/files#diff-38c07265109dbf75e42adf00a5ffd7d6R42

In [automatic refresh](https://github.com/jshmrtn/currency-conversion/pull/20/files#diff-38c07265109dbf75e42adf00a5ffd7d6R53) and [manual refresh](https://github.com/jshmrtn/currency-conversion/pull/20/files#diff-38c07265109dbf75e42adf00a5ffd7d6R65) the normal source is used.

**Comment by strzibny** [comment]
`load_callback` made it confusing I guess. I will try this a little later or tomorrow. Feel free to merge and I just recheck the master that things work :)

**Comment by strzibny** [comment]
I rechecked directly in the project I am working on and it seems it works as expected. Many thanks.

**Pull request merged**
