### PR TITLE
Add exchangeratesapi.io support

### PR DESCRIPTION
**Pull request by strzibny**
This should add support for exchangeratesapi free & open source service. It's based on Fixer API so most code is the same. However it's free service so there is no token and I felt it might be cleaner and better path for the future to have it separately rather then adjusting the Fixer file. What do you think?

### CODE REVIEW

**Review by maennchen — CHANGES_REQUESTED** [review]
Could you mention the new source here: https://github.com/jshmrtn/currency-conversion/blob/master/README.md#configuration ?

**Comment by strzibny** [comment]
Yes, will do.

**Comment by strzibny** [comment]
I added it and made both link to the their respective services.

**Review by maennchen — APPROVED** [review]
Perfect

**Pull request merged**
